"""
Student information for this assignment:

On my/our honor, Maria Berroa and Seraphym Ignacio, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1:
UT EID 2:
"""


def row_zigzag_traversal(grid):
    """
    Performs a zigzag traversal of a 2D list, alternating between
    left-to-right and right-to-left traversal for each row from
    top-to-bottom, and returns a list of coordinates (row, column).

    pre:
    - grid is a 2D list representing a 2D matrix.
    - The rows and columns range from 1 to 10 (inclusive).
    - All rows in grid have the same number of columns.

    post:
    - Returns a list of tuples (row, column) representing the
      coordinates of all elements in the specified order.
    """
    rows = len(grid)
    cols = len(grid[0])
    result = []

    for r in range(rows):
        if r % 2 == 0:
            for c in range(cols):
                result.append((r,c))
        else:
            for c in reversed(range(cols)):
                result.append((r,c))
    return result


def column_zigzag_traversal(grid):
    """
    Performs a zigzag traversal of a 2D list, alternating between
    top-to-bottom and bottom-to-top traversal for each column from
    left-to-right, and returns a list of coordinates (row, column).

    pre:
    - grid is a 2D list representing a 2D matrix.
    - The rows and columns range from 1 to 10 (inclusive).
    - All rows in grid have the same number of columns.

    post:
    - Returns a list of tuples (row, column) representing the
      coordinates of all elements in the specified order.
    """
    rows = len(grid)
    cols = len(grid[0])
    result = []

    for c in range(cols):
        if c % 2 == 0:
            for r in range(rows):
                result.append((r,c))
        else:
            for r in reversed(range(rows)):
                result.append((r,c))
    return result

def main_diagonal_traversal(grid):
    """
    Performs a diagonal traversal of a 2D list, iterating from 
    the top-right to the bottom-left in the direction of the 
    main diagonal, and returns a list of coordinates (row, column).

    pre:
    - grid is a 2D list representing a 2D matrix.
    - The rows and columns range from 1 to 10 (inclusive).
    - All rows in grid have the same number of columns.

    post:
    - Returns a list of tuples (row, column) representing the
      coordinates of all elements in the specified order.
    """

    rows = len(grid)
    cols = len(grid[0])
    result_upper = []
    result_lower = []

    # Upper part of the matrix

    for c in range(cols-1,-1,-1):
        row = 0
        col = c

        while row < rows and col < cols:
            result_upper.append((row,col))
            row += 1
            col += 1

    # Lower part of the matrix

    for r in range(1, rows):
        row = r
        col = 0

        while row < rows and col < cols:
            result_lower.append((row,col))
            row += 1
            col += 1

    result = result_upper + result_lower
    return result


def secondary_diagonal_traversal(grid):
    """
    Performs a diagonal traversal of a 2D list, iterating from 
    the top-left to the bottomt-right in the direction of the 
    main diagonal, and returns a list of coordinates (row, column).

    pre:
    - grid is a 2D list representing a 2D matrix.
    - The rows and columns range from 1 to 10 (inclusive).
    - All rows in grid have the same number of columns.

    post:
    - Returns a list of tuples (row, column) representing the
      coordinates of all elements in the specified order.
    """
    rows = len(grid)
    cols = len(grid[0])
    result_upper = []
    result_lower = []

    # Upper part of the matrix

    for c in range(cols):
        row = 0
        col = c

        while row < rows and col >= 0:
            result_upper.append((row,col))
            row += 1
            col -= 1

    # Lower part of the matrix

    for r in range(1,rows):
        row = r
        col = cols-1

        while row < rows and col >= 0:
            result_lower.append((row,col))
            row += 1
            col -= 1

    result = result_upper + result_lower
    return result


def spiral_traversal(grid):
    """
    Performs a spiral traversal of a 2D list, iterating from 
    the outside rows and columns inward, and returns a list
    of coordinates (row, column).

    pre:
    - grid is a 2D list representing a 2D matrix.
    - The rows and columns range from 1 to 10 (inclusive).
    - All rows in grid have the same number of columns.

    post:
    - Returns a list of tuples (row, column) representing the
      coordinates of all elements in the specified order.
    """

    top = 0
    bottom = len(grid) -1
    left = 0
    right = len(grid[0])-1
    result = []

    while left <= right and top <= bottom:
        for c in range(left,right +1):
            result.append((top,c))
        top +=1

        for r in range(top,bottom +1):
            result.append((r,right))
        right -=1

        if top <= bottom:
            for c in range(right, left-1,-1):
                result.append((bottom,c))
            bottom -=1

        if left <= right:
            for r in range(bottom,top-1,-1):
                result.append((r,left))
            left += 1

    return result
